use( "IndexNormalizer" );
use( "UnitTest" );

UnitTest.addFixture( "IndexNormalizer.normalizeValues", function( ) {

    index = [ {
            name: "dkcclterm.aj",
            value: "20111212180236"
        }, {
            name: "dkcclterm.\xE5r",
            value: "2011 "
        }, {
            name: "dkcclterm.\xE5r",
            value: "2011"
        }, {
            name: "dkcclterm.\xE5r",
            value: "2011"
        }, {
            name: "dkcclterm.cl",
            value: "65.908"
        }, {
            name: "dkcclterm.cl",
            value: "62.8"
        }, {
            name: "dkcclterm.db",
            value: ""
        }, {
            name: "dkcclterm.db",
            value: "sfart"
        }, {
            name: "dkcclterm.db",
            value: ""
        }, {
            name: "dkcclterm.db",
            value: "historie"
        }, {
            name: "dkcclterm.db",
            value: ""
        }, {
            name: "dkcclterm.db",
            value: "skibe"
        }, {
            name: "dkcclterm.db",
            value: ""
        }, {
            name: "dkcclterm.db",
            value: "rederier"
        }, {
            name: "dkcclterm.db",
            value: ""
        }, {
            name: "dkcclterm.db",
            value: "shipping"
        }, {
            name: "dkcclterm.db",
            value: ""
        }, {
            name: "dkcclterm.db",
            value: "containerskibe"
        }, {
            name: "dkcclterm.db",
            value: ""
        }, {
            name: "dkcclterm.db",
            value: "containertransport"
        }, {
            name: "dkcclterm.db",
            value: ""
        }, {
            name: "dkcclterm.db",
            value: "1900-1999"
        }, {
            name: "dkcclterm.db",
            value: ""
        }, {
            name: "dkcclterm.db",
            value: "2000-2009"
        }, {
            name: "dkcclterm.db",
            value: ""
        }, {
            name: "dkcclterm.db",
            value: "2010-2019"
        }, {
            name: "dkcclterm.df",
            value: "sfart"
        }, {
            name: "dkcclterm.df",
            value: "historie"
        }, {
            name: "dkcclterm.df",
            value: "skibe"
        }, {
            name: "dkcclterm.df",
            value: "rederier"
        }, {
            name: "dkcclterm.df",
            value: "shipping"
        }, {
            name: "dkcclterm.df",
            value: "containerskibe"
        }, {
            name: "dkcclterm.df",
            value: "containertransport"
        }, {
            name: "dkcclterm.dk",
            value: "65.908"
        }, {
            name: "dkcclterm.dk",
            value: "62.8"
        }, {
            name: "dkcclterm.ek",
            value: ""
        }, {
            name: "dkcclterm.ek",
            value: "Maersk Line"
        }, {
            name: "dkcclterm.ek",
            value: ""
        }, {
            name: "dkcclterm.ek",
            value: "Det \u00a4stasiatiske Kompagni"
        }, {
            name: "dkcclterm.fl",
            value: "Nautilus"
        }, {
            name: "dkcclterm.fo",
            value: "Peter"
        }, {
            name: "dkcclterm.fo",
            value: "Bruce"
        }, {
            name: "dkcclterm.fo",
            value: "aut"
        }, {
            name: "dkcclterm.hm",
            value: "xx"
        }, {
            name: "dkcclterm.ht",
            value: "Dansk linjefart - fra Selandia til Emma Mrsk"
        }, {
            name: "dkcclterm.ib",
            value: "9788790924102"
        }, {
            name: "dkcclterm.id",
            value: "29036640"
        }, {
            name: "dkcclterm.is",
            value: "9788790924102"
        }, {
            name: "dkcclterm.ka",
            value: "l"
        }, {
            name: "dkcclterm.ka",
            value: "v"
        }, {
            name: "dkcclterm.ke",
            value: "sfart"
        }, {
            name: "dkcclterm.ke",
            value: "historie"
        }, {
            name: "dkcclterm.ke",
            value: "skibe"
        }, {
            name: "dkcclterm.ke",
            value: "rederier"
        }, {
            name: "dkcclterm.ke",
            value: "shipping"
        }, {
            name: "dkcclterm.ke",
            value: "containerskibe"
        }, {
            name: "dkcclterm.ke",
            value: "containertransport"
        }, {
            name: "dkcclterm.ke",
            value: "1900-1999"
        }, {
            name: "dkcclterm.ke",
            value: "2000-2009"
        }, {
            name: "dkcclterm.ke",
            value: "2010-2019"
        }, {
            name: "dkcclterm.kk",
            value: "ACC201143"
        }, {
            name: "dkcclterm.kk",
            value: "DBF201150"
        }, {
            name: "dkcclterm.kk",
            value: "BKM201150"
        }, {
            name: "dkcclterm.ln",
            value: "870970"
        }, {
            name: "dkcclterm.ma",
            value: "xx"
        }, {
            name: "dkcclterm.no",
            value: "Indhold: Skibsdieselmotorens tidlige udvikling ; Udviklingen af dansk linjefart og Selandias betydning ; Grundlggelsen af Dampskibsselskabet af 1912 ; Frste Verdenskrig og tiden efter ; A.P. Mller gr ind i linjefarten ; Efter brskrakket i 1929 ; Anden Verdenskrig ; Linjenettet genetableres ; Containeriseringen og K ; K's svanesang ; Containeriseringen af Maersk Line ; Post-panamax skibe og globalisering ; Vkst gennem opkb ; De lysebl giganter ; Maersk Line nu og i fremtiden"
        }, {
            name: "dkcclterm.nr",
            value: "29036640"
        }, {
            name: "dkcclterm.nr",
            value: "9788790924102"
        }, {
            name: "dkcclterm.ok",
            value: "65.908"
        }, {
            name: "dkcclterm.op",
            value: "20111027"
        }, {
            name: "dkcclterm.pe",
            value: "Peter"
        }, {
            name: "dkcclterm.pe",
            value: "Bruce"
        }, {
            name: "dkcclterm.pe",
            value: "aut"
        }, {
            name: "dkcclterm.po",
            value: "Peter"
        }, {
            name: "dkcclterm.po",
            value: "Bruce"
        }, {
            name: "dkcclterm.po",
            value: "aut"
        }, {
            name: "dkcclterm.pu",
            value: "Frederiksvrk"
        }, {
            name: "dkcclterm.sf",
            value: "201150"
        }, {
            name: "dkcclterm.sf",
            value: "l"
        }, {
            name: "dkcclterm.sf",
            value: "v"
        }, {
            name: "dkcclterm.sp",
            value: "dan"
        }, {
            name: "dkcclterm.ti",
            value: "In the wake of Selandia - danish liner shipping 1912-2012"
        }, {
            name: "dkcclterm.ti",
            value: "Dansk linjefart - fra Selandia til Emma Mrsk"
        }, {
            name: "dkcclterm.ul",
            value: "dk"
        }, {
            name: "dkcclterm.uu",
            value: "nt"
        }, {
            name: "display.title",
            value: "\\tenor saxofon\\"
        }
    ];
    indexOut = [ {
            name: "dkcclterm.aj",
            value: "20111212180236"
        }, {
            name: "dkcclterm.\xE5r",
            value: "2011"
        }, {
            name: "dkcclterm.\xE5r",
            value: "2011"
        }, {
            name: "dkcclterm.\xE5r",
            value: "2011"
        }, {
            name: "dkcclterm.cl",
            value: "65.908"
        }, {
            name: "dkcclterm.cl",
            value: "62.8"
        }, {
            name: "dkcclterm.db",
            value: "sfart"
        }, {
            name: "dkcclterm.db",
            value: "historie"
        }, {
            name: "dkcclterm.db",
            value: "skibe"
        }, {
            name: "dkcclterm.db",
            value: "rederier"
        }, {
            name: "dkcclterm.db",
            value: "shipping"
        }, {
            name: "dkcclterm.db",
            value: "containerskibe"
        }, {
            name: "dkcclterm.db",
            value: "containertransport"
        }, {
            name: "dkcclterm.db",
            value: "1900-1999"
        }, {
            name: "dkcclterm.db",
            value: "2000-2009"
        }, {
            name: "dkcclterm.db",
            value: "2010-2019"
        }, {
            name: "dkcclterm.df",
            value: "sfart"
        }, {
            name: "dkcclterm.df",
            value: "historie"
        }, {
            name: "dkcclterm.df",
            value: "skibe"
        }, {
            name: "dkcclterm.df",
            value: "rederier"
        }, {
            name: "dkcclterm.df",
            value: "shipping"
        }, {
            name: "dkcclterm.df",
            value: "containerskibe"
        }, {
            name: "dkcclterm.df",
            value: "containertransport"
        }, {
            name: "dkcclterm.dk",
            value: "65.908"
        }, {
            name: "dkcclterm.dk",
            value: "62.8"
        }, {
            name: "dkcclterm.ek",
            value: "Maersk Line"
        }, {
            name: "dkcclterm.ek",
            value: "Det stasiatiske Kompagni"
        }, {
            name: "dkcclterm.fl",
            value: "Nautilus"
        }, {
            name: "dkcclterm.fo",
            value: "Peter"
        }, {
            name: "dkcclterm.fo",
            value: "Bruce"
        }, {
            name: "dkcclterm.fo",
            value: "aut"
        }, {
            name: "dkcclterm.hm",
            value: "xx"
        }, {
            name: "dkcclterm.ht",
            value: "Dansk linjefart - fra Selandia til Emma Mrsk"
        }, {
            name: "dkcclterm.ib",
            value: "9788790924102"
        }, {
            name: "dkcclterm.id",
            value: "29036640"
        }, {
            name: "dkcclterm.is",
            value: "9788790924102"
        }, {
            name: "dkcclterm.ka",
            value: "l"
        }, {
            name: "dkcclterm.ka",
            value: "v"
        }, {
            name: "dkcclterm.ke",
            value: "sfart"
        }, {
            name: "dkcclterm.ke",
            value: "historie"
        }, {
            name: "dkcclterm.ke",
            value: "skibe"
        }, {
            name: "dkcclterm.ke",
            value: "rederier"
        }, {
            name: "dkcclterm.ke",
            value: "shipping"
        }, {
            name: "dkcclterm.ke",
            value: "containerskibe"
        }, {
            name: "dkcclterm.ke",
            value: "containertransport"
        }, {
            name: "dkcclterm.ke",
            value: "1900-1999"
        }, {
            name: "dkcclterm.ke",
            value: "2000-2009"
        }, {
            name: "dkcclterm.ke",
            value: "2010-2019"
        }, {
            name: "dkcclterm.kk",
            value: "ACC201143"
        }, {
            name: "dkcclterm.kk",
            value: "DBF201150"
        }, {
            name: "dkcclterm.kk",
            value: "BKM201150"
        }, {
            name: "dkcclterm.ln",
            value: "870970"
        }, {
            name: "dkcclterm.ma",
            value: "xx"
        }, {
            name: "dkcclterm.no",
            value: "Indhold: Skibsdieselmotorens tidlige udvikling ; Udviklingen af dansk linjefart og Selandias betydning ; Grundlggelsen af Dampskibsselskabet af 1912 ; Frste Verdenskrig og tiden efter ; A.P. Mller gr ind i linjefarten ; Efter brskrakket i 1929 ; Anden Verdenskrig ; Linjenettet genetableres ; Containeriseringen og K ; K's svanesang ; Containeriseringen af Maersk Line ; Post-panamax skibe og globalisering ; Vkst gennem opkb ; De lysebl giganter ; Maersk Line nu og i fremtiden"
        }, {
            name: "dkcclterm.nr",
            value: "29036640"
        }, {
            name: "dkcclterm.nr",
            value: "9788790924102"
        }, {
            name: "dkcclterm.ok",
            value: "65.908"
        }, {
            name: "dkcclterm.op",
            value: "20111027"
        }, {
            name: "dkcclterm.pe",
            value: "Peter"
        }, {
            name: "dkcclterm.pe",
            value: "Bruce"
        }, {
            name: "dkcclterm.pe",
            value: "aut"
        }, {
            name: "dkcclterm.po",
            value: "Peter"
        }, {
            name: "dkcclterm.po",
            value: "Bruce"
        }, {
            name: "dkcclterm.po",
            value: "aut"
        }, {
            name: "dkcclterm.pu",
            value: "Frederiksvrk"
        }, {
            name: "dkcclterm.sf",
            value: "201150"
        }, {
            name: "dkcclterm.sf",
            value: "l"
        }, {
            name: "dkcclterm.sf",
            value: "v"
        }, {
            name: "dkcclterm.sp",
            value: "dan"
        }, {
            name: "dkcclterm.ti",
            value: "In the wake of Selandia - danish liner shipping 1912-2012"
        }, {
            name: "dkcclterm.ti",
            value: "Dansk linjefart - fra Selandia til Emma Mrsk"
        }, {
            name: "dkcclterm.ul",
            value: "dk"
        }, {
            name: "dkcclterm.uu",
            value: "nt"
        }, {
            name: "display.title",
            value: "tenor saxofon"
        }
    ];

    Assert.equal( "Normalize index", 'IndexNormalizer.normalizeValues( index );', indexOut );

    delete this.index;
    delete this.indexOut;

} );
