version: "3.3"

services:
  db:
    image: docker-os.dbc.dk/docstore_postgres_demo:latest
    ports:
      - "5000:5432"

  docstore-service:
    build:
    #../service/src/main/docker
      #context: ../
      context: ../service/src/main/docker/
      dockerfile: Dockerfile
    container_name: docstore-server-container
    ports:
      - "8080:8080"
      #- "5432:5432"
    environment:
      #- DOCSTORE_POSTGRES_URL=${DOCSTORE_POSTGRES_URL:-${USER}:${USER}@192.168.9.5:5432/${USER}}
      - DOCSTORE_POSTGRES_URL=test_db:test_db@db:5432/test_db
    volumes:
      - ${PWD}/../service/target/solr-doc-store-service-1.0-SNAPSHOT.war:/payara-micro/wars/solr-doc-store-service-1.0-SNAPSHOT.war

  docstore-dev-server:
    build: .
    container_name: docstore-dev-server-container
    ports:
      - "8090:8090"
    volumes:
      - .:/usr/src/app/:rw
    environment:
      - NODE_ENV=development
      - IS_DOCKERIZED=true

networks:
  default:
    #external:
    #  name: docker_default
    ipam:
      driver: default
      config:
        - subnet: 10.10.11.1/22
