ALTER TABLE queue
  ADD COLUMN classifier VARCHAR(16) NOT NULL DEFAULT 'UNSET';

ALTER TABLE queue
  ALTER COLUMN classifier DROP DEFAULT;

ALTER TABLE queue_error
  ADD COLUMN classifier VARCHAR(16) NOT NULL DEFAULT 'UNSET';

ALTER TABLE queue_error
  ALTER COLUMN classifier DROP DEFAULT;
