INSERT INTO resource (AGENCYID, BIBLIOGRAPHICRECORDID, FIELD, VALUE) VALUES (870970, '11111111', 'hasCoverUrl', true);
INSERT INTO resource (AGENCYID, BIBLIOGRAPHICRECORDID, FIELD, VALUE) VALUES (870970, '11111111', 'hasBackCoverUrl', false);
INSERT INTO resource (AGENCYID, BIBLIOGRAPHICRECORDID, FIELD, VALUE) VALUES (870970, '11111111', 'includesCD', true);


INSERT INTO openagencycache (AGENCYID, LIBRARYTYPE, PARTOFBIBDK, PARTOFDANBIB, AUTHCREATECOMMONRECORD, FETCHED)
VALUES (870970, 'NonFBS', false, false, false, now());